osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

addons:
  apt:
    packages:
      - lynx

os:
  - linux
  - osx

before_install:
  - npm install -g electron
  - npm install -g electron-forge
  - ls
  - npm install
  - ls
  - ln -s ../node_modules node_modules
  - ls ../
  - ls
  - printf Y\n | electron-forge import .
  - lynx -dump ../

install:
  - electron-forge package
