osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

os:
  - linux
  - osx

before_install:
  - sudo apt-get install tree -y
  - npm install -g electron
  - npm install -g electron-forge
  - ls
  - npm install
  - ls
  - ln -s ../node_modules node_modules
  - ls ../
  - ls
  - tree

install:
  - electron-forge make
