


osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

os:
  - linux
  - osx

before_install:
  - npm install -g electron --unsafe-perm=true --allow-root
  - npm install -g electron-forge --unsafe-perm=true --allow-root
  - npm install electron-compile
  - npm install electron-compilers
  - npm install react
  - ls
  - npm install
  - ls
  - ln -s ../node_modules node_modules
  - ls ../
  - ls
  - printf Y\n | electron-forge import .

install:
  - electron-forge make
